import Head from 'next/head'
import { useState } from 'react'
import { signUpNewUser } from '../utils/auth';
export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          sign up
          <form>
            <input type="email" name="email" id="email" placeholder=' Enter Email' onChange={(e) => setEmail(e.target.value)}/>
            <input type="password" name="password" id="password" placeholder=' Enter Password'  onChange={(e) => setPassword(e.target.value)}/>
            <input type="password" name="confirmPassword" id="confirmPassword" placeholder=' Confirm Password' />
            <button onClick={(e) => {
              e.preventDefault();
              signUpNewUser(email, password)
            }}>
              Sign Up
            </button>
          </form>
        </div>
      </main>
    </>
  )
}
