import Head from 'next/head'
import { SignUpForm, SignInForm } from '@/componets/forms'
import useSession from '@/hooks/useSession';
import { signOutUser } from '@/utils/auth';

export default function Home() {
  const {data, error} = useSession();

  if(!data || !data.session) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <SignInForm />
          <SignUpForm />
        </main>
      </>
    )
  }

  return (
    <div>
      {data.session.user.email}

      <button onClick={async () => { await signOutUser() }} >Sign Out</button>
    </div>
  )
  
}
