import Head from 'next/head'
import { useEffect, useState } from 'react';
import { SignUpForm, SignInForm } from '@/componets/forms'
import { getSession } from '@/utils/auth'

export default function Home() {
  const [session, setSession] = useState<{data: any, error: any}>({data: null, error: null})
  console.log(session.data)
  useEffect(() => {
    (async () => {
      setSession(await getSession())
    })();
  }, [])

  if(!session) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <SignInForm />
          <SignUpForm />
        </main>
      </>
    )
  }

  return (
    <div>
      {session.data.session.user.email}
    </div>
  )
  
}
